### ISSUE TITLE
Didn't find the Python3 script to flag spurious variants within sequences

### ISSUE THREAD

**Issue by AlbertRockG** [HussinLab/covid19_mostefai2021_paper#1]
Hello everyone,
I hope you are well.
I am trying to replicate your study on my own data and flag spurious variants. However, I cannot find these scripts in your repository as stated in the paper. Could you please help me?

**Comment by jcgrenier** [comment]
Hello @AlbertRockG , thanks for reaching us. The code is made available in another repository.

https://github.com/HussinLab/Stretch-of-N

Hope it helps you!

**Comment by AlbertRockG** [comment]
Hi @jcgrenier, thanks for sharing the codes. But I still have a few questions. Firstly, I would like to know how to construct the alignment file in fasta format. My second question is about the ImputeCoVNet software, which I haven't found yet. Finally, I also need the Incremental PCA script. I hope you could help us. Thanks in advance.

**Comment by AlbertRockG** [comment]
@jcgrenier @RaphaelRaphael, thank you guys very much, I noticed that the Incremental PCA script has been added to the repository.

**Comment by jcgrenier** [comment]
Yes, sorry, we didn't notice you of that change! Hope this will help!

**Comment by RaphaelRaphael** [comment]
Hi Albert, sorry, I am not use to get my git notifications, Did you found a way to get an alignment ? If you use GISAID data you can just download their fasta file, If not you can use any NGS  pipeline

**Comment by AlbertRockG** [comment]
Thanks @RaphaelRaphael for your help. I am planning to convert my bam file to fasta using this pipeline:

`samtools view -bS alignments.sam > alignments.bam`
`samtools sort alignments.bam -o sorted.bam`
`samtools index sorted.bam`
`samtools fasta -1 -0 -F 4 -s <refname>.fa sorted.bam > aligned_sequences.fa`

So please do let me know what you have to say about it.

**Comment by RaphaelRaphael** [comment]
This is valid but really basic, I think the discussion is going far from the issue but you will find a pipe line described in the method of the paper.
